version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      gatsby:
        patterns:
          - 'gatsby*'
      jest:
        patterns:
          - '@types/jest*'
          - 'jest*'
      react:
        patterns:
          - '@types/react-dom'
          - '@types/react'
          - 'react-dom'
          - 'react'
      stylelint:
        patterns:
          - 'stylelint*'
